// flow-typed signature: 79e1a3bcb1c68f27444744bc88d91a73
// flow-typed version: <<STUB>>/cosmiconfig_v2.2.2/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cosmiconfig'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cosmiconfig' {
  declare module.exports: any;
}
