// flow-typed signature: 559e61a46ad3138f253dac354e0559f3
// flow-typed version: <<STUB>>/tapable_v0.2.8/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tapable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tapable' {
  declare module.exports: any;
}
