// flow-typed signature: a350845d027d85845d7b8ff29874b82f
// flow-typed version: <<STUB>>/worker-farm_v1.5.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'worker-farm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'worker-farm' {
  declare module.exports: any;
}
